<?php

/**
 * User: xwk
 * Date: 2017/3/29
 * Time: 11:01
 */
class Api_Comment extends PhalApi_Api
{
    public function getRules()
    {
//      return parent::getRules(); // TODO: Change the autogenerated stub
        return array(
            'getCommentList' => array(),
            'getComment' => array(
                'c_id' => array('name' => 'c_id', 'require' => false, 'desc' => '课程编号')
            ),
            'delComment' => array(
                'id' => array('name' => 'id', 'require' => true, 'desc' => 'id')
            ),
            'batchDelComment' => array(
                'ids' => array('name' => 'ids', 'require' => true, 'desc' => 'ids')
            )
        );
    }

    //获得评论列表
    public function getCommentList()
    {
        $domain = new Domain_Comment();
        $rs = $domain->getCommentList();

        return $rs;
    }

    //获取文章评论列表
    public function getComment()
    {

        $domain = new Domain_Comment();
        $rs = $domain->getComment($this->c_id);
        return $rs;
    }

    //删除评论
    public function delComment()
    {

        $domain = new Domain_Comment();
        $rs = $domain->delComment($this->id);
        return $rs;
    }

    //批量删除
    public function batchDelComment()
    {
        $domain = new Domain_Comment();
        $rs = $domain->batchDelComment($this->ids);
        return $rs;
    }


}
