<?php

/**
 * User: xwk
 * Date: 2017/3/29
 * Time: 11:01
 */
class Api_Comment extends PhalApi_Api
{
    //localhost/studyApi/PhalApi/Public/?service=Comment.getCommentList
    public function getRules()
    {
//      return parent::getRules(); // TODO: Change the autogenerated stub
        return array(
            'getCommentList' => array(
                'course_id'=>array('name'=>'course_id')
            ),
            'getComment' => array(
                'c_id' => array('name' => 'c_id', 'require' => false, 'desc' => '课程编号')
            ),
            'delComment' => array(
                'id' => array('name' => 'id', 'require' => true, 'desc' => 'id')
            ),
            'batchDelComment' => array(
                'ids' => array('name' => 'ids', 'require' => true, 'desc' => 'ids')
            ),
            'getCommentTitle' => array(
                'c_id' => array('name' => 'c_id', 'require' => true, 'desc' => 'c_id')
            ),
//            $this->course_id,$this->parent_id,$this->nickname,$this->creat_time,$this->content
            'addCommentHead' => array(
                'course_id' => array('name' => 'course_id', 'require' => true),
                'parent_id' => array('name' => 'parent_id', 'require' => true),
                'nickname' => array('name' => 'nickname', 'require' => true),
                'create_time' => array('name' => 'create_time', 'require' => true),
                'content' => array('name' => 'content', 'require' => true)
            ),

        );
    }

    //获得评论列表
    public function getCommentList()
    {
        $domain = new Domain_Comment();
        $rs = $domain->getCommentList($this->course_id);

        return $rs;
    }

    //获取文章评论列表
    public function getComment()
    {

        $domain = new Domain_Comment();
        $rs = $domain->getComment($this->c_id);
        return $rs;
    }

    //删除评论
    public function delComment()
    {

        $domain = new Domain_Comment();
        $rs = $domain->delComment($this->id);
        return $rs;
    }

    //批量删除
    public function batchDelComment()
    {
        $domain = new Domain_Comment();
        $rs = $domain->batchDelComment($this->ids);
        return $rs;
    }

    //获取讨论区内容
    public function getCommentTitle(){

        $domain = new Domain_Comment();
        $rs = $domain -> getCommentTitle($this->c_id);
        return $rs;
    }

    //新建顶层讨论
    public function addCommentHead(){

        $domain = new Domain_Comment();
        $rs = $domain -> addCommentHead($this->course_id,$this->parent_id,$this->nickname,$this->create_time,$this->content);
        return $rs;
    }


}
