<?php
/**
 * User: xwk
 * Date: 2017/3/29
 * Time: 11:01
 */
class Api_Comment extends PhalApi_Api
{
  public function getRules()
  {
//      return parent::getRules(); // TODO: Change the autogenerated stub
      return array(
          'getCommentList'=>array(
            
          )
      );
  }

     //获得评论列表
    public function getCommentList()
    {
        $domain=new Domain_Comment();
        $rs=$domain->getCommentList();

        return $rs;
    }

 
}
