<?php
/**
 * Created by PhpStorm.
 * User: xwk
 * Date: 2017/3/14
 * Time: 15:48
 */
class Api_Course extends PhalApi_Api
{
    //localhost/studyApi/PhalApi/Public/?service=Course.addCourse
  public function getRules()
  {
//      return parent::getRules(); // TODO: Change the autogenerated stub
      return array(
          'addCourse'=>array(
              'name'=>array('name'=>'name','require'=>true,'desc' => '课程作者'),
              'c_name'=>array('name'=>'c_name','require'=>true,'desc' => '课程名称'),
              'c_no'=>array('name'=>'c_no','require'=>true,'desc' => '课程编号(唯一)'),
              'c_start'=>array('name'=>'c_start','type'=>'date','require'=>true,'desc' => '课程开始时间'),
              'c_end'=>array('name'=>'c_end','type'=>'date','require'=>true,'desc' => '课程结束时间'),
              'c_classify'=>array('name'=>'c_classify','require'=>true,'desc' => '课程分类'),
              'c_introduce'=>array('name'=>'c_introduce','require'=>true,'desc' => '课程介绍'),
              'c_exmine'=>array('name'=>'c_exmine','require'=>true,'desc' => '审核状况'),
              'file' => array(
                  'name' => 'file',
                  'type' => 'file',
                  'min' => 0,
                  'max' => 1024 * 1024,
                  'range' => array('image/jpg', 'image/jpeg', 'image/png'),
                  'ext' => array('jpg', 'jpeg', 'png'),
                  'desc' => '文件'
              ),
          ),
          'getCoursesList'=>array(
              'c_no'=>array('name'=>'c_no','require'=>false,'desc' => '课程编号(唯一)')
          ),
          'getCourseListTeacher'=>array(
              'name'=>array('name'=>'name','require'=>true,'desc'=>'作者')
          ),
          'selectCourseDetail'=>array(
              'course_id'=>array('name'=>'course_id','require'=>true,'desc' => '课程编号(唯一)')

          ),
          'removeCourse'=>array(
              'course_id'=>array('name'=>'course_id','require'=>false,'desc'=>'课程编号(唯一)')
          ),
//          $course_id,$c_name,$c_no,$c_introduce,$c_classify,$c_start,$c_end
          'updateCourse'=>array(
              'course_id'=>array('name'=>'course_id','require'=>true,'desc'=>'课程编号(唯一)'),
              'c_name'=>array('name'=>'c_name','require'=>true),
              'c_no'=>array('name'=>'c_no','require'=>true),
              'c_introduce'=>array('name'=>'c_introduce','require'=>true),
              'c_classify'=>array('name'=>'c_classify','require'=>true),
              'c_start'=>array('name'=>'c_start','require'=>true),
              'c_end'=>array('name'=>'c_end','require'=>true)
          ),
          'getCoursesExmine'=>array(
              'course_id'=>array('name'=>'course_id','require'=>false,'desc'=> '课程编号(唯一)'),
              'c_exmine'=>array('name'=>'c_exmine','require'=>true,'desc'=>'课程审核状态')
          ),
          'examineCourse'=>array(
              'course_id'=>array('name'=>'course_id','require'=>true,'desc'=>'课程编号(唯一)'),
              'option'=>array('name'=>'option','require'=>true,'desc'=>'具体课程操作(2:通过，1：不通过)')

          ),
          'batchExamineCourse'=>array(
              'courseNos'=>array('name'=>'courseNos','require'=>true,'desc'=>'课程编号数组'),
              'option'=>array('name'=>'option','require'=>true,'desc'=>'具体课程操作(2:通过，1：不通过)')
          ),
          'selectCourseByPM'=>array(
                'isLimit'=>array('name'=>'isLimit','require'=>true,'desc'=>'是否取前4')
          ),
          'selectCourseByCat'=>array(

          ),
          'uploadVideo'=>array(
              'file' => array(
                  'name' => 'file',
                  'type' => 'file',
                  'desc' => '文件'
              ),
          ),
          'selectCourseByCourse'=>array(
              'c_id'=>array(
                  'name'=>'c_id',
                  'require'=>true
              )
          ),
//          $this->c_id,$this->capter_id,$this->c_content,$this->capter_introduce,$this->c_url
          'addCourseChapter'=>array(
              'dataArr'=>array('name'=>'dataArr','require'=>'true','type'=>'array')
          ),
          'getCourseChapter'=>array(
              'course_id'=>array(
                  'name'=>'course_id','require'=>true
              )
          ),
          'selectCourseByPMId'=>array(
              'c_id'=>array(
                  'name'=>'c_id','require'=>true
              )
          ),
//          $this->name,$this->course,$this->score
          'addStudentCourse'=>array(
              'name'=>array('name'=>'name','require'=>true),
              'course'=>array('name'=>'course','require'=>true),
              'score'=>array('name'=>'score','require'=>true),
              'isFill'=>array('name'=>'isFill','require'=>true)
          ),
//          $this->name,$this->course,$this->score
          'markScore'=>array(
              'name'=>array('name'=>'name','require'=>true),
              'course'=>array('name'=>'course','require'=>true),
              'score'=>array('name'=>'score','require'=>true),
              'isFill'=>array('name'=>'isFill','require'=>true)
          ),
          'selScore'=>array(
              'name'=>array('name'=>'name','require'=>true),
              'course'=>array('name'=>'course','require'=>true)
          ),
          'searchCourse'=>array(
              'key'=>array('name'=>'key','require'=>true)
          ),
          'findCourse'=>array(),
          'findCourseSelected'=>array(
              'name'=>array('name'=>'name','require'=>true)
          ),
          'removeCourseC'=>array(
              'id'=>array('name'=>'id','require'=>true)
          )
      );
  }

    public  function addCourse(){
        //设置上传路径 设置方法参考3.2
        DI()->ucloud->set('save_path', date('Y/m/d'));

        //新增修改文件名设置上传的文件名称
        DI()->ucloud->set('file_name', time());

        //上传表单名
        $r = DI()->ucloud->upfile($this->file);
        $domain=new Domain_Course();
        $res = $domain->addCourse($this->name,$this->c_name,$this->c_no,$this->c_start,$this->c_end,$this->c_classify,$this->c_introduce,$this->c_exmine,$r['url']);
        return $res;
//        $domain=new Domain_Course();
//        $res=$domain->addCourse($this->c_name,$this->c_no,$this->c_start,$this->c_end,$this->c_classify,$this->c_introduce);
//        return $res;
    }

    //上传课程详细章节
    public function addCourseChapter(){
        $domain=new Domain_Course();
        return $domain->addCourseChapter($this->dataArr);
    }

    //获得所有课程列表
    public function getCoursesList()
    {
        $domain=new Domain_Course();
        $rs=$domain->getCoursesList($this->c_no);

        return $rs;
    }

    //教师查看个人课程列表
    public function getCourseListTeacher(){
        $domain=new Domain_Course();
        return $domain->getCourseListTeacher($this->name);
    }

    //修改课程(根据课程id)
    public function updateCourse(){
        $domain=new Domain_Course();
        return $domain->updateCourse($this->course_id,$this->c_name,$this->c_no,$this->c_introduce,$this->c_classify,$this->c_start,$this->c_end);
    }

    //删除课程(根据课程id)
    public function removeCourse(){

        $domain=new Domain_Course();
        $rs=$domain->removeCourse($this->course_id);
        return $rs;
    }

    //查看课程详细
    public function selectCourseDetail(){
        $domain=new Domain_Course();
        $rs=$domain->selectCourseDetail($this->course_id);
        return $rs;
    }
    //只查看课程章节表信息
    public function getCourseChapter(){
        $domain=new Domain_Course();
        $rs=$domain->getCourseChapter($this->course_id);

        return $rs;

    }

    //管理员查看审核课程内容
    public function getCoursesExmine(){

        $domain=new Domain_Course();
        $rs=$domain->getCourseExmine($this->course_id,$this->c_exmine);

        return $rs;
    }

    //管理员审核课程  （0->审核中,1->审核未通过,2->审核通过）
    public function examineCourse(){
        $domain=new Domain_Course();
        $rs=$domain->examineCourse($this->course_id,$this->option);
        return $rs;
    }

    //管理员批量审核课程 （0->审核中,1->审核未通过,2->审核通过）
    public function batchExamineCourse(){
        $domain=new Domain_Course();
        $domain->batchExamineCourse($this->courseNos,$this->option);

    }

    //获取选课学生最多的前4课程
    public function selectCourseByPM(){
        $domain=new Domain_Course();
        $rs=$domain->selectCourseByPM($this->isLimit);
        return $rs;
    }

    public function selectCourseByPMId(){

        $domain=new Domain_Course();
        $rs=$domain->selectCourseByPMId($this->c_id);
        return $rs;
    }

    //按课程分类查询
    public function selectCourseByCat(){
        $domain=new Domain_Course();
        $rs=$domain->selectCourseByCat();
        return $rs;
    }


    //视频上传
    public function uploadVideo(){
        //设置上传路径 设置方法参考3.2
        DI()->ucloud->set('save_path', date('Y/m/d'));

        //新增修改文件名设置上传的文件名称
        DI()->ucloud->set('file_name', time());

        //上传表单名
        $r = DI()->ucloud->upfile($this->file);
        return $r['url'];
    }

    //学生选课
    public function addStudentCourse(){
        $domain=new Domain_Course();
        $rs=$domain->addStudentCourse($this->name,$this->course,$this->score,$this->isFill);
        return $rs;
    }

    //获得选课学生信息
    public function selectCourseByCourse(){
        $domain=new Domain_Course();
        $rs=$domain->selectCourseByCourse($this->c_id);
        return $rs;
    }

    //修改练习题分数
    public function markScore(){

        $domain=new Domain_Course();
        $rs=$domain->markScore($this->name,$this->course,$this->score,$this->isFill);
        return $rs;
    }

    public function selScore(){

        $domain=new Domain_Course();
        $rs=$domain->selScore($this->name,$this->course);
        return $rs;
    }

    //模糊搜索查询课程
    public function searchCourse(){

        $domain=new Domain_Course();
        $rs=$domain->searchCourse($this->key);
        return $rs;
    }

    //查询首页显示的课程
    public function findCourse(){

        $domain=new Domain_Course();
        $rs=$domain->findCourse();
        return $rs;
    }

    //学生查看选择课程
    public function findCourseSelected(){

        $domain=new Domain_Course();
        $rs=$domain->findCourseSelected($this->name);
        return $rs;
    }
    //删除课程章节
    public function removeCourseC(){

        $domain=new Domain_Course();
        $rs=$domain->removeCourseC($this->id);
        return $rs;
    }
}
