<?php
/**
 * Created by PhpStorm.
 * User: xwk
 * Date: 2017/3/14
 * Time: 15:48
 */
class Api_Course extends PhalApi_Api
{
    //localhost/studyApi/PhalApi/Public/?service=Course.addCourse
  public function getRules()
  {
//      return parent::getRules(); // TODO: Change the autogenerated stub
      return array(
          'addCourse'=>array(
              'c_name'=>array('name'=>'c_name','require'=>true,'desc' => '课程名称'),
              'c_no'=>array('name'=>'c_no','require'=>true,'desc' => '课程编号(唯一)'),
              'c_start'=>array('name'=>'c_start','type'=>'date','require'=>true,'desc' => '课程开始时间'),
              'c_end'=>array('name'=>'c_end','type'=>'date','require'=>true,'desc' => '课程结束时间'),
              'c_classify'=>array('name'=>'c_classify','require'=>true,'desc' => '课程分类'),
              'c_introduce'=>array('name'=>'c_introduce','require'=>true,'desc' => '课程介绍'),
              'c_img'=>array('name'=>'c_img','require'=>true,'desc'=>'课程封面')
          ),
          'getCoursesList'=>array(
              'c_no'=>array('name'=>'c_no','require'=>false,'desc' => '课程编号(唯一)')
          ),
          'selectCourseDetail'=>array(
              'course_id'=>array('name'=>'course_id','require'=>true,'desc' => '课程编号(唯一)')

          ),
          'removeCourse'=>array(
              'course_id'=>array('name'=>'course_id','require'=>false,'desc'=>'课程编号(唯一)')
          ),
          'getCoursesExmine'=>array(
              'course_id'=>array('name'=>'course_id','require'=>false,'desc'=> '课程编号(唯一)'),
              'c_exmine'=>array('name'=>'c_exmine','require'=>true,'desc'=>'课程审核状态')
          ),
          'examineCourse'=>array(
              'course_id'=>array('name'=>'course_id','require'=>true,'desc'=>'课程编号(唯一)'),
              'option'=>array('name'=>'option','require'=>true,'desc'=>'具体课程操作(2:通过，1：不通过)')

          ),
          'batchExamineCourse'=>array(
              'courseNos'=>array('name'=>'courseNos','require'=>true,'desc'=>'课程编号数组'),
              'option'=>array('name'=>'option','require'=>true,'desc'=>'具体课程操作(2:通过，1：不通过)')
          ),
          'selectCourseByPM'=>array(

          ),
          'selectCourseByCat'=>array(

          )
      );
  }

    public  function addCourse(){
        $domain=new Domain_Course();
        $res=$domain->addCourse($this->c_name,$this->c_no,$this->c_start,$this->c_end,$this->c_classify,$this->c_introduce);
        return $res;
    }

    //获得所有课程列表
    public function getCoursesList()
    {
        $domain=new Domain_Course();
        $rs=$domain->getCoursesList($this->c_no);

        return $rs;
    }

    //删除课程(根据课程id)
    public function removeCourse(){

        $domain=new Domain_Course();
        $rs=$domain->removeCourse($this->course_id);
        return $rs;
    }

    //查看课程详细
    public function selectCourseDetail(){
        $domain=new Domain_Course();
        $rs=$domain->selectCourseDetail($this->course_id);
        return $rs;
    }

    //管理员查看审核课程内容
    public function getCoursesExmine(){

        $domain=new Domain_Course();
        $rs=$domain->getCourseExmine($this->course_id,$this->c_exmine);

        return $rs;
    }

    //管理员审核课程  （0->审核中,1->审核未通过,2->审核通过）
    public function examineCourse(){
        $domain=new Domain_Course();
        $rs=$domain->examineCourse($this->course_id,$this->option);
        return $rs;
    }

    //管理员批量审核课程 （0->审核中,1->审核未通过,2->审核通过）
    public function batchExamineCourse(){
        $domain=new Domain_Course();
        $domain->batchExamineCourse($this->courseNos,$this->option);

    }

    //获取选课学生最多的前4课程
    public function selectCourseByPM(){
        $domain=new Domain_Course();
        $rs=$domain->selectCourseByPM();
        return $rs;
    }

    //按课程分类查询
    public function selectCourseByCat(){
        $domain=new Domain_Course();
        $rs=$domain->selectCourseByCat();
        return $rs;
    }
}
