<?php

/**
 * Created by PhpStorm.
 * User: xwk
 * Date: 2017/3/31
 * Time: 11:48
 */
class Api_Exercise extends PhalApi_Api
{
    //localhost/studyApi/PhalApi/Public/?service=Exercise.getExercise
    public function getRules()
    {
//      return parent::getRules(); // TODO: Change the autogenerated stub
        return array(
            'getExercise' => array(
                'c_id' => array('name' => 'c_id', 'require' => false, 'desc' => '课程编号')
            ),
            'delExercise' => array(
                'id' => array('name' => 'id', 'require' => true, 'desc' => 'id')
            ),
            'batchDelExercise' => array(
                'ids' => array('name' => 'ids', 'require' => true, 'desc' => 'ids')
            ),
//            $id, $content, $right_option, $option_1, $option_2, $option_3, $score
            'updateExercise' => array(
                'id' => array('name' => 'id', 'require' => true, 'desc' => 'id'),
                'c_id' => array('name' => 'c_id', 'require' => true, 'desc' => 'c_id'),
                'content' => array('name' => 'content', 'require' => true, 'desc' => '习题内容'),
                'right_option' => array('name' => 'right_option', 'require' => true, 'desc' => '正确选项'),
                'option_1' => array('name' => 'option_1', 'require' => true, 'desc' => '选项一'),
                'option_2' => array('name' => 'option_2', 'require' => true, 'desc' => '选项二'),
                'option_3' => array('name' => 'option_3', 'require' => true, 'desc' => '选项三'),
                'score' => array('name' => 'score', 'require' => true, 'desc' => '分值')

            )
        );
    }


    public function getExercise()
    {
        $domain = new Domain_Exercise();
        return $domain->getExercise($this->c_id);
    }

    public function delExercise()
    {
        $domain = new Domain_Exercise();
        return $domain->delExercise($this->id);
    }

    public function batchDelExercise()
    {
        $domain = new Domain_Exercise();
        $domain->batchDelExercise($this->ids);
    }

    public function updateExercise()
    {
        $domain = new Domain_Exercise();
        return $domain->updateExercise($this->id, $this->c_id, $this->content, $this->right_option, $this->option_1, $this->option_2, $this->option_3, $this->score);
    }


}