<?php

/**
 * Created by PhpStorm.
 * User: xwk
 * Date: 2017/3/14
 * Time: 13:46
 */
class Api_User extends PhalApi_Api
{

    public function getRules()
    {
        //localhost/studyApi/PhalApi/Public/?service=User.login
//        return parent::getRules(); // TODO: Change the autogenerated stub
        return array(
            'getUsersByName' => array(
                'name' => array('name' => 'login_name', 'require' => true, 'desc' => '登录用户名')
            ),
            'getUsersList' => array(
                'name' => array('name' => 'name', 'require' => false, 'desc' => '登录用户名')
            ),
            'getUsersListPage' => array(
                'name' => array('name' => 'name', 'require' => false, 'desc' => '登录用户名'),
                'page' => array('name' => 'page', 'require' => true, 'desc' => '第几页')
            ),
            'registerUser' => array(
                'name' => array('name' => 'name', 'require' => true, 'desc' => '登录用户名'),
                'pwd' => array('name' => 'user_pwd', 'require' => true, 'desc' => '登录密码'),
                'sex' => array('name' => 'sex', 'require' => true, 'desc' => '性别'),
                'role' => array('name' => 'role', 'type' => 'int', 'require' => true, 'desc' => '用户角色'),
                'email' => array('name' => 'email', 'require' => true, 'desc' => '注册邮箱'),
                'txUrl' => array('name' => 'tx_url', 'desc' => '头像地址'),
            ),
            'login' => array(
                'name' => array('name' => 'login_name', 'require' => true, 'desc' => '登录用户名'),
                'pwd' => array('name' => 'login_pwd', 'require' => true, 'desc' => '登录密码')

            ),
            'delUser' => array(
                'name' => array('name' => 'name', 'require' => true, 'desc' => '登录用户名')
            ),
            'delUserBatch' => array(
                'names' => array('name' => 'names', 'require' => true, 'desc' => '批量删除名')
            ),
            'updateUser' => array(
                'id' => array('name' => 'id', 'require' => true, 'desc' => '用户id'),
                'name' => array('name' => 'name', 'require' => true, 'desc' => '登录用户名'),
                'pwd' => array('name' => 'user_pwd', 'require' => true, 'desc' => '登录密码'),
                'sex' => array('name' => 'sex', 'require' => true, 'desc' => '性别'),
                'role' => array('name' => 'role', 'type' => 'int', 'require' => true, 'desc' => '用户角色'),
                'email' => array('name' => 'email', 'require' => true, 'desc' => '注册邮箱'),

            ),
            'uploadTx' => array(
                'name' => array(
                    'name' => 'name',
                    'desc' => '登录用户名'
                ),
                'file' => array(
                    'name' => 'file',
                    'type' => 'file',
                    'min' => 0,
                    'max' => 1024 * 1024,
                    'range' => array('image/jpg', 'image/jpeg', 'image/png'),
                    'ext' => array('jpg', 'jpeg', 'png'),
                    'desc' => '文件'
                ),
            ),
        );
    }

    //根据用户名查找
    public function getUsersByName()
    {
        $domain = new Domain_User();

        $rs = $domain->getUsersByName($this->name);
        if (empty($rs)) {
            DI()->logger->debug('user not found', $this->name);
            return $rs;
        }
        return $rs;
    }

    //获取用户列表
    public function getUsersList()
    {
        $domain = new Domain_User();
        $rs = $domain->getUsersList($this->name);
        return $rs;
    }

    //分页获取用户列表
    public function getUsersListPage()
    {
        $domain = new Domain_User();
        $rs = $domain->getUsersListPage($this->name, $this->page);

        return $rs;

    }

    //注册添加新用户
    public function registerUser()
    {
        $domain = new Domain_User();
//        var_dump($this->name,$this->pwd,$this->sex,$this->role,$this->email,$this->txUrl);die();
        $rs = $domain->registerUser($this->name, $this->pwd, $this->sex, $this->role, $this->email, $this->txUrl);
        return $rs;
    }

    //用户登录 （根据pwd和login_name查找role,tx_url,name）
    public function login()
    {
        $model = new Domain_User();
        $rs = $model->login($this->name, $this->pwd);
        if ($rs == false) {
            $rs = 'login_err';
        }
        return $rs;
    }

    //删除用户
    public function delUser()
    {
        $domain = new Domain_User();
        $rs = $domain->delUser($this->name);
        return $rs;
    }

    //批量删除
    public function delUserBatch()
    {
        $domain = new Domain_User();
        $domain->delUserBatch($this->names);
    }

    //修改用户(根据用户id)
    public function updateUser()
    {
        $domain = new Domain_User();
        $rs = $domain->updateUser($this->id, $this->name, $this->pwd, $this->sex, $this->role, $this->email);

        return $rs;
    }


    //上传头像
    public function uploadTx()
    {
        //设置上传路径 设置方法参考3.2
        DI()->ucloud->set('save_path', date('Y/m/d'));

        //新增修改文件名设置上传的文件名称
        DI()->ucloud->set('file_name', time());

        //上传表单名
        $r = DI()->ucloud->upfile($this->file);
        $domain = new Domain_User();
        $res = $domain->updateTx($this->name, $r['url']);
        if ($res == 1) {
            return $r['url'];
        } else {
            return 0;
        }


    }

}